
import type { AppProps } from "next/app";
import Head from "next/head";
import MainLayout from "../components/main-layout/main-layout";
// import { RouteGuard } from "@guards";
import "../styles/globals.css";
import "../public/css/font.css";
import "../public/css/bootstrap.css";
// import "../styles/antd.less"
// import "antd/dist/antd.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main dir={"rtl"}>
        <MainLayout>
          <Component {...pageProps} />
        </MainLayout>
        {/* <RouteGuard>
          
        </RouteGuard> */}
      </main>
    </>
  );
}

export default MyApp;
