import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import "antd/dist/antd.less";
import PanelLayout from "../components/panel-layout/panel-layout";
// import { RouteGuard } from "@guards";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main dir={"rtl"}>
        <PanelLayout>
          <Component {...pageProps} />
        </PanelLayout>
        {/* <RouteGuard>
          
        </RouteGuard> */}
      </main>
    </>
  );
}

export default MyApp;
